# Generated by Django 5.1.2 on 2024-10-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendancerecord',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Leave', 'Leave'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half-day', 'Half-day')], default='Present', max_length=10),
        ),
    ]
